sudo: false
language: d
d:
#  - dmd-nightly
#  - dmd-beta
  - dmd
#  - ldc-beta
#  - ldc

os:
  - linux
#  - osx

#before_install:
#    - gem install fpm
#    - curl -XGET -L -k 'https://api.bintray.com/content/jfrog/jfrog-cli-go/$latest/jfrog-cli-linux-amd64/jfrog?bt_package=jfrog-cli-linux-amd64' > /tmp/jfrog ;
#    - chmod a+x /tmp/jfrog ;
#    - sudo cp /tmp/jfrog /usr/local/bin/jfrog ;

env:
    matrix:
        - BUILD=
#        - BUILD=dub
    global:
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

install: beaver docker build .

script: 
    - beaver docker run dmd -v
    - beaver docker run make pkg

deploy:
    provider: script
    script: beaver bintray upload -N build/last/pkg/*.deb
    skip_cleanup: true
    on:
        tags: true # must be a git tag
        repo: stefan-koch-sociomantic/dfmt # must be me!
