sudo: false
language: d
d:
  - dmd-nightly
  - dmd-beta
  - dmd
  - ldc-beta
  - ldc

os:
  - linux
  - osx

env:
    matrix:
        - BUILD=
        - BUILD=dub
    global:
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

script : .travis.sh
