sudo: false
language: d
d:
#  - dmd-nightly
#  - dmd-beta
  - dmd
#  - ldc-beta
#  - ldc

os:
  - linux
#  - osx

env:
    matrix:
        - BUILD=
#        - BUILD=dub
    global:
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

script: ./.travis.sh

jobs:
    include:
        - stage: Build & Upload Package
          if: tag IS present
          # Which package to deploy
          env:
              - DMD=2.077.*
              - DIST=xenial
              - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"
          language: generic
          sudo: required
          services:
              - docker
          git:
              submodules: false
          before_install: git submodule update --init
          install: beaver docker build .
          script:
              - beaver docker run make pkg
              - beaver bintray upload -N -d dlang-community/apt build/last/pkg/*.deb
