sudo: false
language: d

os:
  - linux

env:
    matrix:
        - BUILD=
        - BUILD=dub
    global:
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"

install: beaver docker build .

script: 
    - beaver docker run make pkg

deploy:
    provider: script
    script: beaver bintray upload -N build/last/pkg/*.deb
    skip_cleanup: true
    on:
        tags: true # must be a git tag
        repo: dlang-community/dfmt #must be in main repo
